version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$FLUORINE_PACKAGE-$FLUORINE_STREAM.$FLUORINE_VERSION --build-arg PACKAGE=$FLUORINE_PACKAGE --build-arg STREAM=$FLUORINE_STREAM --build-arg VERSION=$FLUORINE_VERSION .
      - docker tag $IMAGE_REPO_NAME:$FLUORINE_PACKAGE-$FLUORINE_STREAM.$FLUORINE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$FLUORINE_PACKAGE-$FLUORINE_STREAM.$FLUORINE_VERSION      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$FLUORINE_PACKAGE-$FLUORINE_STREAM.$FLUORINE_VERSION